version: "3.8"
services:
  # node_app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./src/:/app/src/
  #     - .env/:/app/.env
  #   restart: unless-stopped
  #   depends_on:
  #     - node_db
  node_db:
    # image: postgis/postgis
    build: .
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - .env/:/app/.env
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS:"--data-checksums=false"

    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
